[app]
name= "deep-research"
model_id = "moonshotai/Kimi-K2-Thinking"
model_provider = "auto"
task_planner_model_id="deepseek-ai/DeepSeek-V3.2-Exp"
task_planner_provider= "together"
coordinator_model_id = "MiniMaxAI/MiniMax-M1-80k"
subagent_model_id="MiniMaxAI/MiniMax-M1-80k"